### ISSUE TITLE
Json result file not generating for http_request experiment

### ISSUE THREAD

**Issue by cguerrave** [iclab/centinel#109]
Testing with the http_request and the site 666games.net (the first site in the citizen lab list of global sites for testing) for example, I got an error of character imposible to decode and the json file was not generated. It seems to be related to the body insertion in the results file. I fixed this in the line 135 of client.py adding encoding="ISO-8859-1" to the json.dump instruction. I don't know if this is the right way to fix this but it worked for me and because of that I prefer you to see this for yourselves. I tried using utf-8 too but without success.

**Comment by rpanah** [comment]
I found another instance of this. I think this comes from an HTTP request.
```
Traceback (most recent call last):
  File "./centinel.py", line 109, in <module>
    client.run()
  File "/home/abbas/iclab/centinel/centinel/client.py", line 207, in run
    json.dump(results, result_file, indent = 2, separators=(',', ': '))
  File "/usr/lib/python2.7/json/__init__.py", line 189, in dump
    for chunk in iterable:
  File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 390, in _iterencode_dict
    yield _encoder(value)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x95 in position 5751: invalid start byte
```

**Comment by rpanah** [comment]
I wrote a patch for the HTTP primitive that makes it fall back on base64 encoding in the event of a UTF-8 encoding failure. It should address the encoding problem, but adds a bit more of processing effort on the server side when experiment results data is going to be moved to the database.
