### ISSUE TITLE
TLS primitive exception

### ISSUE THREAD

**Issue by lianke123321** [iclab/centinel#187]
I saw this a lot when running tls experiment:

```
2015-10-06 02:47:09,132: INFO: Running TLS certificate requests...
Exception in thread Thread-265:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/adrian/project/adrian-centinel/centinel/primitives/tls.py", line 26, in get_fingerprint
    ssl_version=ssl.PROTOCOL_TLSv1)
  File "/usr/lib/python2.7/ssl.py", line 965, in get_server_certificate
    with closing(context.wrap_socket(sock)) as sslsock:
  File "/usr/lib/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 566, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 788, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:581)
```

**Comment by rpanah** [comment]
Shouldn't this happen the other way around? We should fall back on SSLv3 only when TLSv1 is not supported.
