### ISSUE TITLE
Exception in dnslib primitive

### ISSUE THREAD

**Issue by lianke123321** [iclab/centinel#197]
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/adrian/projects/adrian-centinel/centinel/primitives/dnslib.py", line 168, in lookup_domain
    resp = dns.message.from_wire(response)
  File "/usr/local/lib/python2.7/dist-packages/dns/message.py", line 790, in from_wire
    reader.read()
  File "/usr/local/lib/python2.7/dist-packages/dns/message.py", line 726, in read
    self._get_question(qcount)
  File "/usr/local/lib/python2.7/dist-packages/dns/message.py", line 608, in _get_question
    self.wire[self.current:self.current + 4])
  File "/usr/local/lib/python2.7/dist-packages/dns/wiredata.py", line 55, in __getslice__
    raise dns.exception.FormError
FormError

**Comment by lianke123321** [comment]
primitive should handle this properly

**Comment by rpanah** [comment]
@lianke123321 did you address this issue?

**Comment by lianke123321** [comment]
No, I didn't.
