### ISSUE TITLE
dnspython exception

### ISSUE THREAD

**Issue by lianke123321** [iclab/centinel#214]
Saw this exception why running vpn.py:
```
Exception in thread Thread-1432:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/vagrant/centinel/centinel/primitives/dnslib.py", line 180, in lookup_domain
    resp = dns.message.from_wire(response)
  File "/usr/local/lib/python2.7/dist-packages/dns/message.py", line 790, in from_wire
    reader.read()
  File "/usr/local/lib/python2.7/dist-packages/dns/message.py", line 726, in read
    self._get_question(qcount)
  File "/usr/local/lib/python2.7/dist-packages/dns/message.py", line 602, in _get_question
    (qname, used) = dns.name.from_wire(self.wire, self.current)
  File "/usr/local/lib/python2.7/dist-packages/dns/name.py", line 704, in from_wire
    raise BadPointer
BadPointer
```

**Comment by lianke123321** [comment]
@rpanah can u look into this?

**Comment by rpanah** [comment]
@lianke123321 do you have steps to reproduce?

**Comment by lianke123321** [comment]
@rpanah I was running top-500 baseline experiment while connecting to a purevpn endpoint.

**Comment by lianke123321** [comment]
Another dns exception:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/vagrant/centinel/centinel/primitives/dnslib.py", line 180, in lookup_domain
    resp = dns.message.from_wire(response)
  File "/usr/local/lib/python2.7/dist-packages/dns/message.py", line 790, in from_wire
    reader.read()
  File "/usr/local/lib/python2.7/dist-packages/dns/message.py", line 726, in read
    self._get_question(qcount)
  File "/usr/local/lib/python2.7/dist-packages/dns/message.py", line 602, in _get_question
    (qname, used) = dns.name.from_wire(self.wire, self.current)
  File "/usr/local/lib/python2.7/dist-packages/dns/name.py", line 708, in from_wire
    raise BadLabelType
BadLabelType
```

**Comment by lianke123321** [comment]
@JASONews could you help look into this? Since you wrote dnslib unit test right?

**Comment by rpanah** [comment]
@lianke123321, do you know if this was addressed at any point in time?

**Comment by lianke123321** [comment]
@rpanah no, since it's still open.

**Comment by rpanah** [comment]
@lianke123321 I haven't seen this in the RPi nodes' log files. Did you encounter this with the VPNs again?

**Comment by lianke123321** [comment]
@rpanah I saw this in VPN walker's logs, you might want to check those logs.
