### ISSUE TITLE
Decode exception while saving results

### ISSUE THREAD

**Issue by lianke123321** [iclab/centinel#222]
```
2016-03-09 16:48:57,558 client.py(line 384) ERROR: Error saving results for baseline to file: 'utf8' codec can't decode byte 0xe9 in position 14: invalid continuation byte
Traceback (most recent call last):
  File "/home/vagrant/centinel/centinel/client.py", line 380, in run_exp
    separators=(',', ': '))
  File "/usr/lib/python2.7/json/__init__.py", line 189, in dump
    for chunk in iterable:
  File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 390, in _iterencode_dict
    yield _encoder(value)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 14: invalid continuation byte
```

**Comment by rpanah** [comment]
This has been addressed in 1.5.6.2.
