### ISSUE TITLE
Look into SSL Built In CA Bundle Verification Error

### ISSUE THREAD

**Issue by ben-jones** [iclab/centinel#70]
We are now shipping a copy of our certificate bundle (the validation chain) with our client because we ran into issue verifying the GoDaddy certificate from certain machines.

The error we get from Python requests is:
ben@ben:~$ python
Python 2.7.3 (default, Mar 13 2014, 11:03:55) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> r = requests.get("https://server.iclab.org:8082/geolocation")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 456, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 559, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 382, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

**Comment by rpanah** [comment]
The problem lies in our SSL context setup. SSL intermediate certificate chain was not added to server's SSL context. This issue can be fixed from the server side.
I will remove the cert bundle from the client after I patch the server.
